
services:
  backend:
    build:
      context: ./springboot_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./yamu_frontend
    ports:
      - "5173:80"  # Expose port 80 from container as 5173 on host
